### PR TITLE
Remove Type Hinting for Python 3.4 compatiblity

### PR DESCRIPTION
**Pull request by edjubuh**
Still need to:

[ ] Check that PROS CLI actually works in Python 3.4

### CODE REVIEW

**Comment by edjubuh** [comment]
Tested on khardula

**Review by HotelCalifornia — APPROVED** [review]
Looks good (I really would have done it, you know)

**Comment by edjubuh** [comment]
This will close #10

**Review by jwalk511 — APPROVED** [review]
Installs without error on OS X with Python 3.4

**Pull request merged**
